version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./nginx-entrypoint.sh:/nginx-entrypoint.d/entrypoint.sh
    ports:
      - "80:80"
    depends_on:
      - web
    environment:
      - APP_PORT=3000
      - APP_HOST=web
    entrypoint: ["/bin/sh", "-c", "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
